server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boots_tntproject?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8&useUnicode=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  resources:
    static-locations: classpath:/static,classpath:/templates

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html



